apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-huey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-huey
  template:
    metadata:
      labels:
        app: redis-huey
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
